version: Build-{build}
image: Visual Studio 2017
build_script:
- cmd: dotnet build %APPVEYOR_BUILD_FOLDER%/src /p:Configuration=Release;VersionSuffix=%suffix%
skip_commits:
  files:
    - docs/*
    - readme.md
branches:
  only:
  - develop
  - master
environment:
  versioningScriptsFolder: .\dotnet-versioning-scripts\dotnet-versioning
  packageName: Autofac.BindingByConvention
  csprojPath: .\src\Autofac.BindingByConvention\Autofac.BindingByConvention.csproj
  repoNuGet: https://www.nuget.org/api/v2
install:
- git submodule update --init --recursive
before_build:
- dotnet restore "./src/Autofac.BindingByConvention.sln"
- cmd: %versioningScriptsFolder%/define-version-variables-appveyor.ps1 %csprojPath% %versioningScriptsFolder% %packageName% %APPVEYOR_REPO_BRANCH%
after_build:
 - dotnet pack  ./src --configuration Release --include-symbols --output "%APPVEYOR_BUILD_FOLDER%/artifacts" --no-build --version-suffix %suffix%
artifacts:
- path: ./artifacts/Autofac.BindingByConvention.*.nupkg
  name: NuGet_pkg
# deploy:
# - provider: NuGet
#   server: https://www.nuget.org/api/v2/package
#   artifact: NuGet_pkg
#   api_key:
#     secure: uBphca4OZ4WuDCPtfgBWnGvqvQOirDAq+ErQubkiMwUBVnKfETzoMxsNS/ofyTZJ
#   on:
#     branch: develop
# - provider: NuGet
#   server: https://www.nuget.org/api/v2/package
#   artifact: NuGet_pkg
#   api_key:
#     secure: uBphca4OZ4WuDCPtfgBWnGvqvQOirDAq+ErQubkiMwUBVnKfETzoMxsNS/ofyTZJ
#   on:
#     branch: master
  
