version: Build-{build}
image: Visual Studio 2017
build:
  verbosity: normal
  publish_nuget: true
  publish_nuget_symbols: true
  parallel: true
skip_commits:
  files:
    - docs/*
    - readme.md
branches:
  only:
  - develop
  - master
environment:
  versioningScriptsFolder: C:\projects\autofac-bindingbyconvention-m58p5\dotnet-versioning-scripts\dotnet-versioning
  packageName: Autofac.BindingByConvention
  csprojPath: C:\projects\autofac-bindingbyconvention-m58p5\src\Autofac.BindingByConvention\Autofac.BindingByConvention.csproj
  repoNuGet: https://www.nuget.org/api/v2
install:
- git submodule update --init --recursive
before_build:
- dotnet restore "./src/Autofac.BindingByConvention.sln"
- ps: Add-AppveyorMessage "APPVEYOR_JOB_NAME $env:APPVEYOR_JOB_NAME"
- ps: Add-AppveyorMessage "APPVEYOR_JOB_ID $env:APPVEYOR_JOB_ID"
- ps: Add-AppveyorMessage "APPVEYOR_BUILD_ID $env:APPVEYOR_BUILD_ID"
- ps: Add-AppveyorMessage "APPVEYOR_BUILD_FOLDER $env:APPVEYOR_BUILD_FOLDER"
- ps: Add-AppveyorMessage "APPVEYOR_PROJECT_SLUG $env:APPVEYOR_PROJECT_SLUG"
- ps: Add-AppveyorMessage "APPVEYOR_PROJECT_ID $env:APPVEYOR_PROJECT_ID"
- ps: C:\projects\autofac-bindingbyconvention-m58p5\dotnet-versioning-scripts\dotnet-versioning\define-version-variables-appveyor.ps1 $env:csprojPath $env:versioningScriptsFolder $env:packageName $env:APPVEYOR_REPO_BRANCH
artifacts:
- path: '$env:APPVEYOR_BUILD_FOLDER/Autofac.BindingByConvention.*.symbols.nupkg '
  name: NuGet_pkg
deploy:
- provider: NuGet
  server: https://www.nuget.org/api/v2/package
  artifact: NuGet_pkg
  api_key:
    secure: uBphca4OZ4WuDCPtfgBWnGvqvQOirDAq+ErQubkiMwUBVnKfETzoMxsNS/ofyTZJ
  on:
    branch: develop
- provider: NuGet
  server: https://www.nuget.org/api/v2/package
  artifact: NuGet_pkg
  api_key:
    secure: uBphca4OZ4WuDCPtfgBWnGvqvQOirDAq+ErQubkiMwUBVnKfETzoMxsNS/ofyTZJ
  on:
    branch: master
  
